---
# defaults file for base

# System hostname
base_hostname: "arch"

# System locales
base_locales:
  - "en_US.UTF-8"

# By default the first locale in `base_locales` is used to set the `LANG`
# variable in /etc/locale.conf. This can be overridden by setting the
# `base_lang` variable.
#base_lang: "en_GB.UTF-8"

# System timezone
base_timezone: "America/Chicago"

# Whether the hardware clock is in UTC or in local timezone.
base_hwclock: "UTC" # "UTC" or "local"

# Number of simultaneous threads pacman should be configured to use.
base_pacman_threads: 10

# Packages to install
base_packages:
  - base
  - coreutils
  - man-db
  - man-pages

# Users. Default username:password is archlinux:archlinux.
base_users:
  - name: archlinux
    create_home: yes
    shell: /usr/bin/bash
    password:
      '$6$UCJ6Fj5Fero5.6TT$9zR9pf4e5Whb1EK8GO/uxOLGrs4I217rc2hboq9T59a6En/yMOtojPxaURhHIx4pdcekUXSD9FWdl7eYemRy81'
    groups:
      - adm
      - uucp
      - wheel
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_bits: 521

# When enabled configure opendoas.
base_doas_enabled: yes

# When enabled install microcode updates.
base_ucode_enabled: yes

# Path of grub.cfg
base_grub_cfg: "/boot/grub/grub.cfg"

# When enabled configure dash to be /bin/sh.
base_dash_sh_enabled: yes
