---
- name: Enable color output
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*Color\b.*'
    line: "Color"
    insertafter: "[options]"

- name: Enable parallel downloads
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*ParallelDownloads\b.*'
    line: "ParallelDownloads = {{ pacman_parallel_downloads }}"
    insertafter: "[options]"

- name: Enable I love candy
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    insertafter: '^ParallelDownloads\b.*'
    line: "ILoveCandy"

- block:
  - name: Install pacman-contrib
    community.general.pacman:
      name: pacman-contrib

  - name: Install pacman cache cleanup hook
    ansible.builtin.copy:
      src: pacman-cache-cleanup.hook
      dest: /etc/pacman.d/hooks/
      mode: "0644"
      directory_mode: "0755"
      owner: root
      group: root
    when: pacman_install_cache_cleanup_hook
  when: pacman_install_contrib
