---
# handlers file for networking
- name: restart-networkmanager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted

- name: restart-systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted

- name: restart-iptables
  ansible.builtin.systemd:
    name: iptables.service
    state: restarted
